platform :ios, '12.0'
use_frameworks!


target 'KoalaTransitions_Example' do |target|
  pod 'KoalaTransitions', :path => '../'
  pod 'SnapKit'
  pod 'SwiftyButton'
  pod 'SwiftFormat/CLI'
  pod 'SwiftLint'
  
  script_phase :name => 'swiftformat run', :script => ' ./Pods/SwiftFormat/CommandLineTool/swiftformat .', :execution_position => :before_compile

  script_phase :name => 'swiftformat pod run', :script => ' ./Pods/SwiftFormat/CommandLineTool/swiftformat ../KoalaTransitions', :execution_position => :before_compile
  
  script_phase :name => 'siwftLint run', :script => ' ./Pods/SwiftLint/swiftlint', :execution_position => :before_compile
  
  target 'KoalaTransitions_Tests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'KoalaTransitions'
      target.build_configurations.each do |config|
        if config.name == 'Debug'
            config.build_settings['OTHER_SWIFT_FLAGS'] = '-DDEBUG -Xfrontend -warn-long-function-bodies=50 -Xfrontend -warn-long-expression-type-checking=50'
            else
            config.build_settings['OTHER_SWIFT_FLAGS'] = ''
        end
      end
    end
  end
end

