platform :ios, '12.0'
use_frameworks!


target 'KoalaTransitions_Example' do
  pod 'KoalaTransitions', :path => '../'
  pod 'SnapKit'
  pod 'SwiftyButton'
  pod 'SwiftFormat/CLI'
  pod 'SwiftLint'
  
  script_phase :name => 'swiftformat run', :script => ' ./Pods/SwiftFormat/CommandLineTool/swiftformat .', :execution_position => :before_compile

  script_phase :name => 'swiftformat pod run', :script => ' ./Pods/SwiftFormat/CommandLineTool/swiftformat ../KoalaTransitions', :execution_position => :before_compile
  
  script_phase :name => 'siwftLint run', :script => ' ./Pods/SwiftLint/swiftlint', :execution_position => :before_compile
  
  target 'KoalaTransitions_Tests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end
end
